### ISSUE TITLE
Implement LSPS2: tracking issue

### ISSUE THREAD

**Issue by JssDWt** [breez/breez-sdk#385]
Tracking issue for implementation of the LSPS2 spec into Breez SDK. The corresponding tracking issue for lspd can be found [here](https://github.com/breez/lspd/issues/110)

- [ ] https://github.com/breez/breez-sdk/issues/379
- [ ] https://github.com/breez/breez-sdk/issues/380
- [ ] https://github.com/breez/breez-sdk/issues/381
- [ ] https://github.com/breez/breez-sdk/issues/382
- [ ] https://github.com/breez/breez-sdk/issues/383
- [ ] https://github.com/breez/breez-sdk/issues/384
