### ISSUE TITLE
Roadmap to payment notifications feature

### ISSUE THREAD

**Issue by ok300** [breez/breez-sdk#574]
###  Issues found

- [x] Background thread timeout has limited effect on physical Android
- [x] Occasional "node not initialized" error when app was stopped and notification wakes background thread
- [x] Occasional empty history when app is opened after notification triggered background thread
  - Solved by https://github.com/breez/c-breez/pull/702
- [x] Errors thrown by `connect` take between 30s - 1m 30s to propagate to the UI (Android)

Low prio

- [ ] Validate the notification before processing it
  - if we receive a notification for an unknown payment_hash, the background thread still keeps checking that payment

### Next steps

- [x] LSPD: Add LSPD notification endpoints to Breez Server
- [x] LSPD: Handle stale URLs on LSP, while still supporting multi-device: https://github.com/breez/lspd/pull/147
- [x] SDK: Update notifications branch (SDK) to use Breez Server notifications
  - Pending https://github.com/breez/breez-sdk/pull/597 
- [x] c-breez: Integrate notification calls: https://github.com/breez/c-breez/pull/717
- [x] c-breez: iOS extension for c-breez: https://github.com/breez/c-breez/issues/562
- [x] c-breez: Allow c-breez to stop the GL node: https://github.com/breez/c-breez/pull/720
- [x] Docs / snippets: how to setup: https://github.com/breez/breez-sdk-docs/pull/108

### Open questions

- [x] "Send notifications to multiple endpoints" https://github.com/breez/breez-sdk/issues/112
- [x] Webhooks: possible on tor? Not at the moment.
- [ ] When more notification types are supported:
  - How should the SDK `register_webhook` signature look like? Should it take as arg the desired notification types?
  - Same for LSP: different method for each notification type?
- [x] How to handle the 5 minute time-window, where the LSP may see the node as online but the signer might be offline, and therefore notifications may not be sent

### Future improvements

- https://github.com/breez/lspd/issues/103

**Comment by JssDWt** [comment]
Breez server now has the PaymentNotifier service:
https://github.com/breez/server/blob/d3d5dc9ea267d9c61ef9b4e9ec9096e63bbe1e08/breez/breez.proto#L83-L85

The signature is a recoverable signature over the double hash of the url. It should be signed by the node id, so lspd can extract the node id from the signature.
